##
# Validate credit card number
#
# @credit
# @version 0.1

CC = gcc
CFLAGS = -g -Werror -Wall -lcs50
TARGET = credit

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
		$(RM)(TARGET)
# end
