##
# Mario-more
#
# @file
# @version 0.1

CC=gcc

CFLAGS= -g -Wall -Werror -lcs50

TARGET= mario

all: $(TARGET)

$(TARGET): $(TARGET).c
		$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
		$(RM) $(TARGET)
# end
