##
# Problem Set 1, cash problem
#
# @cash_munra
# @version 0.1

CC = gcc

CFLAGS = -g -Wall -Werror -lcs50

TARGET = cash

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
		$(RM)(TARGET)

# end
